server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
      - id: ASSOCIATE-SERVICE
        uri: lb://ASSOCIATE-SERVICE
        predicates:
        - Path=/pru-associate/**
      - id: SKILL-SERVICE
        uri: lb://SKILL-SERVICE
        predicates:
        - Path=/pru-skill/**
      - id: ONBOARDING-TASK
        uri: lb://ONBOARDING-TASK
        predicates:
        - Path=/task/**

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   
  